#!/bin/bash
fps=10 speed=1 n=1 ss=0 S1="{\\\\fs(60)\\\\c(FFFFFF)}人权的故事\\\\N人权的演进与由来" ./d hr00 https://www.youtube.com/watch?v=UPQ_uaiyYTE
fps=10 speed=1 n=1 ss=0 S1="{\\\\fs(60)\\\\c(FF0000)}人权公益广告\\\\N#1\\\\N我们天生自由而平等" ./d hr01 https://www.youtube.com/watch?v=YvmRLGi1yPw
fps=10 speed=1 n=1 ss=0 S1="{\\\\fs(60)\\\\c(FF4000)}人权公益广告\\\\N#2\\\\N不要有差别待遇" ./d hr02 https://www.youtube.com/watch?v=iggHnjX9zFY
fps=10 speed=1 n=1 ss=0 S1="{\\\\fs(60)\\\\c(FF7000)}人权公益广告\\\\N#3\\\\N生存的权利" ./d hr03 https://www.youtube.com/watch?v=kpHYx-FOXLM
fps=10 speed=1 n=1 ss=0 S1="{\\\\fs(60)\\\\c(FFC000)}人权公益广告\\\\N#4\\\\N不要有奴隶制度" ./d hr04 https://www.youtube.com/watch?v=M_I6AXm2a3g
fps=10 speed=1 n=1 ss=0 S1="{\\\\fs(60)\\\\c(FFFF00)}人权公益广告\\\\N#5\\\\N没有折磨" ./d hr05 https://www.youtube.com/watch?v=gy7Jb3OfEjU
fps=10 speed=1 n=1 ss=0 S1="{\\\\fs(55)\\\\c(C0FF00)}人权公益广告\\\\N#6\\\\N不管到哪里，你都有权利" ./d hr06 https://www.youtube.com/watch?v=K4A37n7z8A0
fps=10 speed=1 n=1 ss=0 S1="{\\\\fs(60)\\\\c(80FF00)}人权公益广告\\\\N#7\\\\N法律之前，人人平等" ./d hr07 https://www.youtube.com/watch?v=7h740KDCyY8
fps=10 speed=1 n=1 ss=0 S1="{\\\\fs(55)\\\\c(50FF00)}人权公益广告\\\\N#8\\\\N你的人权受到法律的保护" ./d hr08 https://www.youtube.com/watch?v=bkuo2Jz4bCw
fps=10 speed=1 n=1 ss=0 S1="{\\\\fs(60)\\\\c(28FF00)}人权公益广告\\\\N#9\\\\N没有不公平的拘留" ./d hr09 https://www.youtube.com/watch?v=fvShFZEQEmQ
fps=10 speed=1 n=1 ss=0 S1="{\\\\fs(60)\\\\c(00FF00)}人权公益广告\\\\N#10\\\\N审判的权利" ./d hr10 https://www.youtube.com/watch?v=qVW-fUcJ2y8
fps=10 speed=1 n=1 ss=0 S1="{\\\\fs(60)\\\\c(00FF40)}人权公益广告\\\\N#11\\\\N直到被证明有罪之前 我们都是清白的" ./d hr11 https://www.youtube.com/watch?v=DP0SHjv5QMw
fps=10 speed=1 n=1 ss=0 S1="{\\\\fs(60)\\\\c(00FF80)}人权公益广告\\\\N#12\\\\N隐私的权利" ./d hr12 https://www.youtube.com/watch?v=NLgpTjzDgGY
fps=10 speed=1 n=1 ss=0 S1="{\\\\fs(60)\\\\c(00FFA0)}人权公益广告\\\\N#13\\\\N行动的自由" ./d hr13 https://www.youtube.com/watch?v=1yIxDPntAX4
fps=10 speed=1 n=1 ss=0 S1="{\\\\fs(60)\\\\c(00FFC0)}人权公益广告\\\\N#14\\\\N寻求安全居所的权利" ./d hr14 https://www.youtube.com/watch?v=11BUtgp57dw
fps=10 speed=1 n=1 ss=0 S1="{\\\\fs(60)\\\\c(00FFFF)}人权公益广告\\\\N#15\\\\N有国籍的权利" ./d hr15 https://www.youtube.com/watch?v=LL288eExm60
fps=10 speed=1 n=1 ss=0 S1="{\\\\fs(60)\\\\c(00D0FF)}人权公益广告\\\\N#16\\\\N婚姻与家庭" ./d hr16 https://www.youtube.com/watch?v=ja3syfHNtYg
fps=10 speed=1 n=1 ss=0 S1="{\\\\fs(60)\\\\c(00A0FF)}人权公益广告\\\\N#17\\\\N拥有属于你自己 东西的权利" ./d hr17 https://www.youtube.com/watch?v=4YFaimvfKdk
fps=10 speed=1 n=1 ss=0 S1="{\\\\fs(60)\\\\c(0080FF)}人权公益广告\\\\N#18\\\\N思想的自由" ./d hr18 https://www.youtube.com/watch?v=EF5U0Mj2Ogc
fps=10 speed=1 n=1 ss=0 S1="{\\\\fs(60)\\\\c(0060FF)}人权公益广告\\\\N#19\\\\N表达的自由" ./d hr19 https://www.youtube.com/watch?v=W5UxjT_vJF8
fps=10 speed=1 n=1 ss=0 S1="{\\\\fs(60)\\\\c(0030FF)}人权公益广告\\\\N#20\\\\N公众集会的权利" ./d hr20 https://www.youtube.com/watch?v=TRRyzUBxo-0
fps=10 speed=1 n=1 ss=0 S1="{\\\\fs(60)\\\\c(0000FF)}人权公益广告\\\\N#21\\\\N民主的权利" ./d hr21 https://www.youtube.com/watch?v=WNe5bED4t00
fps=10 speed=1 n=1 ss=0 S1="{\\\\fs(60)\\\\c(3000FF)}人权公益广告\\\\N#22\\\\N社会保障" ./d hr22 https://www.youtube.com/watch?v=N1B0f-pqEU8
fps=10 speed=1 n=1 ss=0 S1="{\\\\fs(60)\\\\c(6000FF)}人权公益广告\\\\N#23\\\\N工作者的权利" ./d hr23 https://www.youtube.com/watch?v=YuHlwPBBDY4
fps=10 speed=1 n=1 ss=0 S1="{\\\\fs(60)\\\\c(9000FF)}人权公益广告\\\\N#24\\\\N玩的权利" ./d hr24 https://www.youtube.com/watch?v=EfgZW_BrIos
fps=10 speed=1 n=1 ss=0 S1="{\\\\fs(55)\\\\c(B000FF)}人权公益广告\\\\N#25\\\\N所有人都有食物与居所" ./d hr25 https://www.youtube.com/watch?v=CF_aCYd-jXE
fps=10 speed=1 n=1 ss=0 S1="{\\\\fs(60)\\\\c(FF00FF)}人权公益广告\\\\N#26\\\\N接受教育的权利" ./d hr26 https://www.youtube.com/watch?v=nGprJU0sS90
fps=10 speed=1 n=1 ss=0 S1="{\\\\fs(60)\\\\c(FF00C0)}人权公益广告\\\\N#27\\\\N著作权" ./d hr27 https://www.youtube.com/watch?v=rvHC3oU2AyA
fps=10 speed=1 n=1 ss=0 S1="{\\\\fs(60)\\\\c(FF0080)}人权公益广告\\\\N#28\\\\N自由与公平的世界" ./d hr28 https://www.youtube.com/watch?v=3OoMOkDJAek
fps=10 speed=1 n=1 ss=0 S1="{\\\\fs(60)\\\\c(FF0040)}人权公益广告\\\\N#29\\\\N责任" ./d hr29 https://www.youtube.com/watch?v=OG-IUDg9m7M
fps=10 speed=1 n=1 ss=0 S1="{\\\\fs(60)\\\\c(FF0000)}人权公益广告\\\\N#30\\\\N没有任何人可以 剥夺你的人权" ./d hr30 https://www.youtube.com/watch?v=NeMTsRDX9DY
