#!/bin/bash
function gen {
 line=$1
 echo $line
 URL=`echo $line | cut -d '"' -f 1`
 filename=`echo $line | cut -d '"' -f 2`
 filename_withoutext=${filename%.*}
 text=${filename_withoutext#*_}
 echo $text
 m=$target/$filename_withoutext.tmp
 output=$target/$filename_withoutext.jpg
 qrencode -m 2 -s 12 -o $m $base$URL
 convert $m \
        -resize 400x400 \
	-gravity South \
	-extent 400x500 \
	-gravity NorthEast \
        -font Noto-Sans-CJK-JP-Bold \
	-fill blue -pointsize 30 -draw "text 30,0 '每'" \
	-fill red -pointsize 30 -draw "text 2,0 '日'" \
	-fill green -pointsize 30 -draw "text 30,30 '油'" \
	-fill black -pointsize 30 -draw "text 2,30 '兔'" \
	-gravity NorthWest \
	-fill black -pointsize 22 -draw "text 10,10 '$text'" \
        -font Noto-Sans-CJK-JP-Regular \
	-fill red -pointsize 20 -draw "text 10,55 '扫码后如果遇到微信浏览器提示,'" \
	-fill red -pointsize 20 -draw "text 10,80 '请点击底部的\"访问原网页\"。'" \
	-gravity SouthWest \
	-fill red -pointsize 14 -draw "text 3,1 '加微信号wanggonging进群 输浏览器地址45.77.144.52进网盘'" \
	-quality 20  \
	$output
 rm -f $m
}

function sync {
 rsync $1 -av --del ~/OneDrive/每日油兔/ root@45.77.144.52:/var/www/html
}

sync
target=~/OneDrive/每日油兔/本站资料二维码分享
rm -f $target/*.jpg

function onedir {
 base=$1
 wget $base -O index.html
 grep mp4 index.html |tail -n 1000| cut -b 80- | cut -d '/' -f 1 | sed 's/>//' | sed 's/<//' | while read line
 do
   gen $line
 done
 rm -f index.html
}

onedir http://45.77.144.52/
gen '"《每日油兔网盘总目录》'
onedir http://45.77.144.52/2.历史资料/传奇时代/
gen '"《传奇时代子目录》'

sync
rm -f /home/public_share/qr/*.jpg
cp $target/* /home/public_share/qr

#  Font: AR-PL-UKai-CN
#  Font: AR-PL-UKai-HK
#  Font: AR-PL-UKai-TW
#  Font: AR-PL-UKai-TW-MBE
#  Font: AR-PL-UMing-CN
#  Font: AR-PL-UMing-HK
#  Font: AR-PL-UMing-TW
#  Font: AR-PL-UMing-TW-MBE
